### ISSUE TITLE
GradCAM does not match exactly. Why?

### ISSUE THREAD

**Issue by bemoregt** [leftthomas/GradCAM#1]
Hi, @leftthomas 

As a result of classifying with Resnet, Accuarcy is over 99%. If you hit map the object area with gradCAM with that model file, it does not match exactly. Why?
it does not match exactly. Why?

It seems to be a problem of GradCAM rather than Resnet classification learning. The objects to be hit-mapped are not as local or blob like dogs or cats, but close to a long straight line. In this case, GradCAM seems to miss the object area. Have you experienced this?

For a well-trainedd Resnet34 model, how do you optimize GradCAM?

Thanks, in advance.

from @bemoregt.

**Comment by leftthomas** [comment]
@bemoregt I think maybe it is a singularity that your model can not handle, so when you vis it, it produces odd result. The implement of GradCAM is in strict accordance with the idea on that paper.
